# -*- coding: utf-8 -*-
"""image task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10wzexNuPgwv4JwDcL6rrYx-XlZKTjm2E
"""

import cv2 as cv
import matplotlib.pyplot as plt

img = cv.imread("/content/image1.jpg")
img = cv.cvtColor(img, cv.COLOR_BGR2RGB)
plt.axis("off")
plt.title("Origenal")
plt.imshow(img)

red = img[:, :, 0]
green = img[:, :, 1]
blue = img[:, :, 2]

plt.imshow(red, cmap="gray")
plt.axis("off")
plt.title("Red chanel")

plt.hist(red.flatten(), bins=256, color='r')
plt.title("Red Histogram")

plt.imshow(green, cmap="gray")
plt.axis("off")
plt.title("Green Channel")

plt.hist(green.flatten(), bins=256, color='g')
plt.title("Red Histogram")

plt.imshow(blue, cmap="gray")
plt.axis("off")
plt.title("Blue Channel")

plt.hist(blue.flatten(), bins=256, color='b')
plt.title("Blue Histogram")

equalize_red = cv.equalizeHist(red)
plt.imshow(equalize_red, cmap="gray")
plt.axis("off")
plt.title("Equalized Red")

plt.hist(equalize_red.flatten(), bins=256, color='r')
plt.title("Equalized Red Histogram")

equalize_green = cv.equalizeHist(green)
plt.imshow(equalize_green, cmap="gray")
plt.axis("off")
plt.title("Equalized Green")

plt.hist(equalize_green.flatten(), bins=256, color='g')
plt.title("Equalized Green Histogram")

equalize_blue = cv.equalizeHist(blue)
plt.imshow(equalize_blue, cmap="gray")
plt.axis("off")
plt.title("Equalized Blue")

plt.hist(equalize_blue.flatten(), bins=256, color='b')
plt.title("Equalized Blue Histogram")

equalized_rgb = cv.merge([equalize_red, equalize_green, equalize_blue])
plt.imshow(equalized_rgb)
plt.axis("off")
plt.title("Equalized RGB Image")

